[functions.create-player]
verify_jwt = false
enabled = true
entrypoint = "./functions/create-player/index.ts"
import_map = "./functions/create-player/deno.json"

[functions.reset-user-password]
verify_jwt = false
enabled = true
entrypoint = "./functions/reset-user-password/index.ts"
import_map = "./functions/reset-user-password/deno.json"

[functions.repair-user-login]
verify_jwt = false
enabled = true
entrypoint = "./functions/repair-user-login/index.ts"
import_map = "./functions/repair-user-login/deno.json"

[functions.delete-user]
verify_jwt = false
enabled = true
entrypoint = "./functions/delete-user/index.ts"
import_map = "./functions/delete-user/deno.json"
